### ISSUE TITLE
Full-Stack JavaScript Techdegree Unit 7 prerequisite courses to be completed

### ISSUE THREAD

**Issue by kieranbarker** [kieranbarker/Treehouse#2]
#TODO

*Courses left before I can start Unit 7 of my FSJS Techdegree*

* [ ] GitHub Basics
* [ ] Express Basics
* [ ] Understanding Express Middleware
* [ ] Debugging Node Applications with Google Chrome
* [ ] Deploy a Node Application to Heroku

🎉 🎊 🙌 

cc @kieranbarker
